### ISSUE TITLE
All Contributors Bot Commands

### ISSUE THREAD

**Issue by kurozael** [CloudSixteen/HL2RP#1]

**Comment by kurozael** [comment]
@all-contributors please add @kurozael for code, maintenance, design, doc, infra, plugin, security, management and ideas

**Comment by kurozael** [comment]
@all-contributors please add @gr4ss for code

**Comment by kurozael** [comment]
@all-contributors please add @xRJx for code

**Comment by kurozael** [comment]
@all-contributors please add @VortixDev for maintenance and code

**Comment by kurozael** [comment]
@all-contributors please add @alexgrist for code

**Comment by kurozael** [comment]
@all-contributors please add @impulsh for code

**Comment by mark27205** [comment]
@all-contributors please add @mark27205 for test

**Comment by kiobu** [comment]
@all-contributors please add @kiobu  for code, maintenance
