### ISSUE TITLE
Voice Commands not working

### ISSUE THREAD

**Issue by Nightmare-Night** [CloudSixteen/HL2RP#15]
With base clockwork hl2rp installed on a development server with zero modified code, scanners using the dispatch command only play the sound file for the dispatch command as a sort of speaker around the scanner.

MPF1 using a voice command over the radio command with another MPF2 on the same frequency, MPF2 doesn't hear the voice command.

There are no visible errors in console logs saying something is being called that doesn't exist.

**Comment by VortixDev** [comment]
This is related to the voice-chaining change that was introduced to Clockwork - the voices are now stored differently in the message info, which causes HL2RP to improperly set the `info.voice.global` value to true, while the `info.voice` table is no longer used.
